tinymce.addI18n('ar', {
  "#": "#",
  "Accessibility": "سهولة الوصول",
  "Accordion": "",
  "Accordion body...": "",
  "Accordion summary...": "",
  "Action": "الإجراء",
  "Activity": "النشاط",
  "Address": "العنوان",
  "Advanced": "خيارات متقدمة",
  "Align": "محاذاة",
  "Align center": "محاذاة للمنتصف",
  "Align left": "محاذاة إلى اليسار",
  "Align right": "محاذاة إلى اليمين",
  "Alignment": "محاذاة",
  "Alignment {0}": "",
  "All": "الكل",
  "Alternative description": "الوصف البديل",
  "Alternative source": "مصدر بديل",
  "Alternative source URL": "عنوان URL للمصدر البديل",
  "Anchor": "رابط",
  "Anchor...": "مرساة...",
  "Anchors": "مراس",
  "Animals and Nature": "الحيوانات والطبيعة",
  "Arrows": "الأسهم",
  "B": "أزرق",
  "Background color": "لون الخلفية",
  "Background color {0}": "",
  "Black": "أسود",
  "Block": "حظر",
  "Block {0}": "",
  "Blockquote": "اقتباس",
  "Blocks": "الكتل",
  "Blue": "أزرق",
  "Blue component": "المكون الأزرق",
  "Body": "النص",
  "Bold": "غامق",
  "Border": "الحد",
  "Border color": "لون الحد",
  "Border style": "نمط الحد",
  "Border width": "عرض الحد",
  "Bottom": "أسفل",
  "Browse files": "",
  "Browse for an image": "استعراض صورة",
  "Browse links": "",
  "Bullet list": "قائمة تعداد نقطي",
  "Cancel": "إلغاء الأمر",
  "Caption": "شرح",
  "Cell": "خلية",
  "Cell padding": "تبطين الخلية",
  "Cell properties": "خصائص الخلية",
  "Cell spacing": "تباعد الخلايا",
  "Cell styles": "تنسيق الخلية",
  "Cell type": "نوع الخلية",
  "Center": "وسط",
  "Characters": "الأحرف",
  "Characters (no spaces)": "الأحرف (دون المسافات)",
  "Circle": "دائرة",
  "Class": "الفئة",
  "Clear formatting": "مسح التنسيق",
  "Close": "إغلاق",
  "Code": "رمز",
  "Code sample...": "عينة الرمز...",
  "Code view": "عارض الرموز",
  "Color Picker": "منتقي الألوان",
  "Color swatch": "عينات الألوان",
  "Cols": "أعمدة",
  "Column": "عمود",
  "Column clipboard actions": "اجراءات محفظة العامود",
  "Column group": "مجموعة الأعمدة",
  "Column header": "رأس العمود",
  "Constrain proportions": "تقييد التناسب",
  "Copy": "نسخ",
  "Copy column": "نسخ العامود",
  "Copy row": "نسخ الصف",
  "Could not find the specified string.": "تعذر العثور على السلسلة المحددة.",
  "Could not load emojis": "فشل تحميل الأيقونات التعبيرية",
  "Count": "العدد",
  "Currency": "العملة",
  "Current window": "النافذة الحالية",
  "Custom color": "لون مخصص",
  "Custom...": "مخصص...",
  "Cut": "قص",
  "Cut column": "قص العامود",
  "Cut row": "قص الصف",
  "Dark Blue": "أزرق داكن",
  "Dark Gray": "رمادي داكن",
  "Dark Green": "أخضر داكن",
  "Dark Orange": "برتقالي داكن",
  "Dark Purple": "أرجواني داكن",
  "Dark Red": "أحمر داكن",
  "Dark Turquoise": "فيروزي داكن",
  "Dark Yellow": "أصفر داكن",
  "Dashed": "متقطع",
  "Date/time": "التاريخ/الوقت",
  "Decrease indent": "تقليل المسافة البادئة",
  "Default": "افتراضي",
  "Delete accordion": "",
  "Delete column": "حذف عمود",
  "Delete row": "حذف صف",
  "Delete table": "حذف جدول",
  "Dimensions": "الأبعاد",
  "Disc": "قرص",
  "Div": "Div",
  "Document": "المستند",
  "Dotted": "منقط",
  "Double": "مزدوج",
  "Drop an image here": "إفلات صورة هنا",
  "Dropped file type is not supported": "نوع الملف الذي تم اسقاطه غير مدعوم",
  "Edit": "تحرير",
  "Embed": "تضمين",
  "Emojis": "أيقونات تعبيرية",
  "Emojis...": "وجوه تعبيريه...",
  "Error": "خطأ",
  "Error: Form submit field collision.": "خطأ: تضارب في حقل إرسال النموذج.",
  "Error: No form element found.": "الخطأ: لم يتم العثور على عنصر نموذج.",
  "Extended Latin": "اللاتينية الموسعة",
  "Failed to initialize plugin: {0}": "فشلت تهيئة المكوِّن الإضافي: {0}",
  "Failed to load plugin url: {0}": "فشل تحميل url للمكوِّن الإضافي: {0}",
  "Failed to load plugin: {0} from url {1}": "فشل تحميل المكوِّن الإضافي: {0} من url ‏{1}",
  "Failed to upload image: {0}": "فشل تحميل الصورة: {0}",
  "File": "ملف",
  "Find": "بحث",
  "Find (if searchreplace plugin activated)": "البحث (إذا كان المكوِّن الإضافي للبحث مفعلاً)",
  "Find and Replace": "البحث والاستبدال",
  "Find and replace...": "جارٍ البحث والاستبدال...",
  "Find in selection": "البحث بالمحدد",
  "Find whole words only": "بحث كلمات بأكملها فقط",
  "Flags": "العلامات",
  "Focus to contextual toolbar": "التركيز على شريط أدوات السياق",
  "Focus to element path": "التركيز على مسار العنصر",
  "Focus to menubar": "التركيز على شريط القوائم",
  "Focus to toolbar": "التركيز على شريط الأدوات",
  "Font": "الخط",
  "Font size {0}": "",
  "Font sizes": "أحجام الخطوط",
  "Font {0}": "",
  "Fonts": "الخطوط",
  "Food and Drink": "الأطعمة والمشروبات",
  "Footer": "تذييل",
  "Format": "تنسيق",
  "Format {0}": "",
  "Formats": "التنسيقات",
  "Fullscreen": "ملء الشاشة",
  "G": "أخضر",
  "General": "عام",
  "Gray": "رمادي",
  "Green": "أخضر",
  "Green component": "المكون الأخضر",
  "Groove": "فجوة",
  "Handy Shortcuts": "اختصارات مساعِدة",
  "Header": "الرأس ",
  "Header cell": "خلية العنوان",
  "Heading 1": "عنوان 1",
  "Heading 2": "عنوان 2",
  "Heading 3": "عنوان 3",
  "Heading 4": "عنوان 4",
  "Heading 5": "عنوان 5",
  "Heading 6": "عنوان 6",
  "Headings": "العناوين",
  "Height": "الارتفاع",
  "Help": "تعليمات",
  "Hex color code": "كود اللون بصيغة Hex",
  "Hidden": "مخفي",
  "Horizontal align": "محاذاة أفقية",
  "Horizontal line": "خط أفقي",
  "Horizontal space": "مسافة أفقية",
  "ID": "المعرف",
  "ID should start with a letter, followed only by letters, numbers, dashes, dots, colons or underscores.": "يجب أن يبدأ المعرف بحرف ، متبوعًا فقط بأحرف أو أرقام أو شرطات أو نقاط أو نقطتان أو شرطات سفلية.",
  "Image is decorative": "الصورة مزخرفة",
  "Image list": "قائمة الصور",
  "Image title": "عنوان الصورة",
  "Image...": "صورة...",
  "ImageProxy HTTP error: Could not find Image Proxy": "خطأ في عنوان وكيل الصور لـHTTP: لا يمكننا ايجاد وكيل الصورة",
  "ImageProxy HTTP error: Incorrect Image Proxy URL": "عنوان وكيل الصور لـHTTP: عنوان وكيل الصورة خاطئ",
  "ImageProxy HTTP error: Rejected request": "خطأ في عنوان وكيل الصور لـHTTP:: طلب مرفوص",
  "ImageProxy HTTP error: Unknown ImageProxy error": "خطأ في عنوان وكيل الصور لـHTTP: وكيل صورة غير معروف",
  "Increase indent": "زيادة المسافة البادئة",
  "Inline": "داخلي",
  "Insert": "إدراج",
  "Insert Template": "إدخال قالب",
  "Insert accordion": "",
  "Insert column after": "إدراج عمود بعد",
  "Insert column before": "إدراج عمود قبل",
  "Insert date/time": "إدراج تاريخ/وقت",
  "Insert image": "إدراج صورة",
  "Insert link (if link plugin activated)": "إدراج ارتباط (إذا كانت المكوِّن الإضافي للارتباط مفعلاً)",
  "Insert row after": "إدراج صف بعد",
  "Insert row before": "إدراج صف قبل",
  "Insert table": "إدراج جدول",
  "Insert template...": "جارٍ إدراج قالب...",
  "Insert video": "إدراج فيديو",
  "Insert/Edit code sample": "إدراج/تحرير عينة الرمز",
  "Insert/edit image": "إدراج/تحرير صورة",
  "Insert/edit link": "إدراج/تحرير ارتباط",
  "Insert/edit media": "إدراج/تحرير الوسائط المتعددة",
  "Insert/edit video": "إدراج/تحرير فيديو",
  "Inset": "ادرج",
  "Invalid hex color code: {0}": "كود اللون غير صالح: {0}",
  "Invalid input": "مدخل غير سليم",
  "Italic": "مائل",
  "Justify": "ضبط",
  "Keyboard Navigation": "التنقل بواسطة لوحة المفاتيح",
  "Language": "اللغة",
  "Learn more...": "معرفة المزيد...",
  "Left": "يسار",
  "Left to right": "يسار إلى اليمين",
  "Light Blue": "أزرق فاتح",
  "Light Gray": "رمادي فاتح",
  "Light Green": "أخضر فاتح",
  "Light Purple": "بنفسجي فاتح",
  "Light Red": "أحمر فاتح",
  "Light Yellow": "أصفر فاتح",
  "Line height": "ارتفاع الخط",
  "Link list": "قائمة الروابط",
  "Link...": "ارتباط...",
  "List Properties": "قائمة الخصائص",
  "List properties...": "قائمة الخصائص...",
  "Loading emojis...": "جار تحميل أيقونات تعبيرية...",
  "Loading...": "تحميل...",
  "Lower Alpha": "حرف أبجدي صغير",
  "Lower Greek": "حروف يونانية صغيرة",
  "Lower Roman": "حرف لاتيني صغير",
  "Match case": "مطابقة الحالة",
  "Mathematical": "رياضية",
  "Media poster (Image URL)": "ملصق الوسائط (عنوان URL للصورة)",
  "Media...": "الوسائط...",
  "Medium Blue": "أزرق متوسط",
  "Medium Gray": "رمادي متوسط",
  "Medium Purple": "بنفسجي متوسط",
  "Merge cells": "دمج خلايا",
  "Middle": "وسط",
  "Midnight Blue": "أزرق داكن جداً",
  "More...": "المزيد...",
  "Name": "الاسم",
  "Navy Blue": "أزرق نيلي",
  "New document": "مستند جديد",
  "New window": "نافذة جديدة",
  "Next": "التالي",
  "No": "لا",
  "No alignment": "دون محاذاة",
  "No color": "بدون لون",
  "Nonbreaking space": "مسافة غير منقسمة",
  "None": "لا شيء",
  "Numbered list": "قائمة مرقمَّة",
  "OR": "أو",
  "Objects": "كائنات",
  "Ok": "موافق",
  "Open help dialog": "افتح حوار التعليمات",
  "Open link": "فتح الرابط",
  "Open link in...": "جارٍ فتح الارتباط.",
  "Open popup menu for split buttons": "افتح القائمة المنبثقة لأزرار الانقسام",
  "Orange": "برتقالي",
  "Outset": "الاستهلالة",
  "Page break": "فاصل صفحات",
  "Paragraph": "الفقرة",
  "Paste": "لصق",
  "Paste as text": "لصق كنص",
  "Paste column after": "لصق العامود بعد",
  "Paste column before": "لصق العامود قبل",
  "Paste is now in plain text mode. Contents will now be pasted as plain text until you toggle this option off.": "عملية اللصق تتم حاليًا كنص عادي. سيبقى النص عادياً حتى تقوم بتعطيل هذا الخيار.",
  "Paste or type a link": "الصق ارتباط أو اكتبه",
  "Paste row after": "لصق الصف بعد",
  "Paste row before": "لصق الصف قبل",
  "Paste your embed code below:": "لصق رمز التضمين أدناه:",
  "People": "أشخاص",
  "Plugins": "المكوِّنات الإضافية",
  "Plugins installed ({0}):": "المكوِّنات الإضافية المثبتة ({0}):",
  "Powered by {0}": "مدعوم بواسطة {0}",
  "Pre": "قبل",
  "Preferences": "التفضيلات",
  "Preformatted": "منسق مسبقًا",
  "Premium plugins:": "المكوِّنات الإضافية المميزة:",
  "Press the Up and Down arrow keys to resize the editor.": "",
  "Press the arrow keys to resize the editor.": "",
  "Press {0} for help": "",
  "Preview": "معاينة",
  "Previous": "السابق",
  "Print": "طباعة",
  "Print...": "طباعة...",
  "Purple": "بنفسجي",
  "Quotations": "عروض الأسعار",
  "R": "أحمر",
  "Range 0 to 255": "المدى من 0 إلى 255",
  "Red": "أحمر",
  "Red component": "المكون الأحمر",
  "Redo": "إعادة",
  "Remove": "إزالة",
  "Remove color": "إزالة لون",
  "Remove link": "إزالة ارتباط",
  "Replace": "استبدال",
  "Replace all": "استبدال الكل",
  "Replace with": "استبدال بـ",
  "Resize": "تغيير الحجم",
  "Restore last draft": "استعادة آخر مسودة",
  "Reveal or hide additional toolbar items": "",
  "Rich Text Area": "مساحة نَص ال rich",
  "Rich Text Area. Press ALT-0 for help.": "منطقة نص منسق. اضغط ALT-0 للحصول على المساعدة.",
  "Rich Text Area. Press ALT-F9 for menu. Press ALT-F10 for toolbar. Press ALT-0 for help": "منطقة نص منسق. اضغط ALT-F9 للقائمة. اضغط ALT-F10 لشريط الأدوات. اضغط ALT-0 للحصول على المساعدة",
  "Ridge": "تمديد للنهاية",
  "Right": "يمين",
  "Right to left": "يمين إلى اليسار",
  "Row": "صف",
  "Row clipboard actions": "اجراءات محفظة الصف",
  "Row group": "مجموعة الصفوف",
  "Row header": "رأس الصف",
  "Row properties": "خصائص الصف",
  "Row type": "نوع الصف",
  "Rows": "صفوف",
  "Save": "حفظ",
  "Save (if save plugin activated)": "حفظ (إذا كان المكوِّن الإضافي للحفظ مفعلاً)",
  "Scope": "النطاق",
  "Search": "بحث",
  "Select all": "تحديد الكل",
  "Select...": "تحديد...",
  "Selection": "التحديد",
  "Shortcut": "الاختصار",
  "Show blocks": "إظهار الكتل",
  "Show caption": "إظهار التسمية التوضيحية",
  "Show invisible characters": "إظهار الأحرف غير المرئية",
  "Size": "الحجم",
  "Solid": "سميك",
  "Source": "المصدر",
  "Source code": "رمز المصدر",
  "Special Character": "رمز خاص",
  "Special character...": "رمز خاص...",
  "Split cell": "تقسيم خلية",
  "Square": "مربع",
  "Start list at number": "بدء القائمة عند الرقم",
  "Strikethrough": "يتوسطه خط",
  "Style": "النمط",
  "Subscript": "منخفض",
  "Superscript": "مرتفع",
  "Switch to or from fullscreen mode": "التبديل إلى أو من وضع ملء الشاشة",
  "Symbols": "الرموز",
  "System Font": "خط النظام",
  "Table": "جدول",
  "Table caption": "عنوان الجدول",
  "Table properties": "خصائص الجدول",
  "Table styles": "تنسيق الجدول",
  "Template": "القالب",
  "Templates": "القوالب",
  "Text": "النص",
  "Text color": "لون النص",
  "Text color {0}": "",
  "Text to display": "النص المعروض",
  "The URL you entered seems to be an email address. Do you want to add the required mailto: prefix?": "الارتباط الذي قمت بإدراجه يشبه البريد الالكتروني. هل تريد إضافة اللاحقة mailto: المطلوبة؟",
  "The URL you entered seems to be an external link. Do you want to add the required http:// prefix?": "يبدو أن عنوان URL الذي أدخلته يشير إلى ارتباط خارجي. هل تريد إضافة اللاحقة http:// المطلوبة؟",
  "The URL you entered seems to be an external link. Do you want to add the required https:// prefix?": "يبدو أن عنوان URL الذي أدخلته يشير إلى ارتباط خارجي. هل تريد إضافة اللاحقة https:// المطلوبة؟",
  "Title": "العنوان",
  "To open the popup, press Shift+Enter": "لفتح القائمة المنبثقة، اضغط على Shift‏+Enter",
  "Toggle accordion": "",
  "Tools": "الأدوات",
  "Top": "أعلى",
  "Travel and Places": "السفر والأماكن سياحية",
  "Turquoise": "فيروزي",
  "Underline": "تسطير",
  "Undo": "تراجع",
  "Upload": "تحميل",
  "Uploading image": "رفع صورة",
  "Upper Alpha": "حرف أبجدي كبير",
  "Upper Roman": "حرف لاتيني كبير",
  "Url": "رابط",
  "User Defined": "معرَّف من قبل المستخدم",
  "Valid": "صحيح",
  "Version": "الإصدار",
  "Vertical align": "محاذاة عمودية",
  "Vertical space": "مسافة عمودية",
  "View": "عرض",
  "Visual aids": "أدوات المساعدة البصرية",
  "Warn": "تحذير",
  "White": "أبيض",
  "Width": "العرض",
  "Word count": "عدد الكلمات",
  "Words": "الكلمات",
  "Words: {0}": "الكلمات: {0}",
  "Yellow": "أصفر",
  "Yes": "نعم",
  "You are using {0}": "أنت تستخدم {0}",
  "You have unsaved changes are you sure you want to navigate away?": "لديك تغييرات لم يتم حفظها هل تريد بالتأكيد الانتقال بعيدًا؟",
  "Your browser doesn't support direct access to the clipboard. Please use the Ctrl+X/C/V keyboard shortcuts instead.": "متصفحك لا يدعم الوصول المباشر إلى الحافظة. يُرجى استخدام اختصارات لوحة المفاتيح Ctrl+X/C/V بدلاً من ذلك.",
  "_dir": "rtl",
  "alignment": "محاذاة",
  "austral sign": "علامة الأوسترال",
  "cedi sign": "علامة السيدي",
  "colon sign": "علامة النقطتين",
  "cruzeiro sign": "علامة الكروزيرو",
  "currency sign": "علامة عملة",
  "dollar sign": "علامة الدولار",
  "dong sign": "علامة الدونج",
  "drachma sign": "علامة الدراخما",
  "euro-currency sign": "علامة عملة اليورو",
  "example": "مثال",
  "formatting": "تنسيق",
  "french franc sign": "علامة الفرنك الفرنسي",
  "german penny symbol": "علامة البنس الألماني",
  "guarani sign": "علامة الجواراني",
  "history": "المحفوظات",
  "hryvnia sign": "علامة الهريفنيا",
  "indentation": "مسافة بادئة",
  "indian rupee sign": "علامة الروبية الهندية",
  "kip sign": "عملة الكيب",
  "lira sign": "علامة الليرة",
  "livre tournois sign": "علامة ليفر تورنويز",
  "manat sign": "علامة المانات",
  "mill sign": "علامة المل",
  "naira sign": "علامة النيرة",
  "new sheqel sign": "علامة الشيكل الجديد",
  "nordic mark sign": "علامة النوردك",
  "peseta sign": "علامة البيزيتا",
  "peso sign": "علامة البيزو",
  "ruble sign": "علامة الروبل",
  "rupee sign": "علامة الروبية",
  "spesmilo sign": "علامة الاسبيزمايلو",
  "styles": "الأنماط",
  "tenge sign": "علامة التينج",
  "tugrik sign": "عملة التوغريك",
  "turkish lira sign": "علامة الليرة التركية",
  "won sign": "علامة الون",
  "yen character": "علامة الين",
  "yen/yuan character variant one": "العلامة البديلة لعلامة الين/اليوان",
  "yuan character": "علامة اليوان",
  "yuan character, in hong kong and taiwan": "علامة اليوان في هونج كونج وتايوان",
  "{0} characters": "{0} رموز",
  "{0} columns, {1} rows": "",
  "{0} words": "{0} من الكلمات"
});
