name: Update TinyMCE Language Packs

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-langs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Download Language Pack ZIP
        run: |
          curl -L -o langs.zip https://download.tiny.cloud/tinymce/community/languagepacks/6/langs.zip

      - name: Unzip Language Pack
        run: |
          mkdir -p tmp_langs
          unzip langs.zip -d tmp_langs_raw
          mv tmp_langs_raw/langs/* tmp_langs/

      - name: Rename Files to *.es5.js
        run: |
          cd tmp_langs
          for f in *.js; do
            mv "$f" "${f%.js}.es5.js"
          done

      - name: Format JS files for readability
        run: |
          node scripts/format-lang-file.js tmp_langs

      - name: Test formatted language files
        run: |
          node scripts/test-lang-files.js tmp_langs

      - name: Upload language file errors (if any)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: language-file-errors
          path: language-file-errors.md
          if-no-files-found: ignore

      - name: Syncing to target directory
        run: |
          TARGET_DIR="build/media_source/vendor/tinymce/langs/"
          mkdir -p ${TARGET_DIR}
          rsync -i -rptgo --checksum --ignore-times --delete tmp_langs/ ${TARGET_DIR}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update TinyMCE language packs"
          branch: update/tinymce-langs
          title: "Update TinyMCE language packs"
          body: |
            This PR was automatically generated by the GitHub Action workflow.
            It updates the TinyMCE language packs from the latest langs.zip.
          delete-branch: true
